---
title: "Logistic-Regression"
author: "Wilbert"
date: "2023-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load rjags
```{r}
library(rjags)
```

## Load Data
```{r}
set.seed(0820)
Y <- c(64, 72, 55, 27, 75, 24, 28, 66, 40, 13)
N <- c(75, 95, 63, 39, 83, 26, 41, 82, 54, 16)
q <- c(0.845, 0.847, 0.880, 0.674, 0.909, 0.899, 0.770, 0.801, 0.802, 0.875)
       
X <- log(q)-log(1-q) # X = logit(q)
```

## Plot the Data
```{r}
inits <- c("RW","JH","KL","LJ","SC","IT","GA","JW","AD","KD")
plot(100*q,100*Y/N,
     xlim=100*c(0.65,0.95),ylim=100*c(0.65,0.95),
     xlab="Overall percentage",ylab="Clutch percentage")
text(100*q,100*Y/N+1,inits)
abline(0,1)
```

## Modeling
```{r}
data <- list(Y=Y,N=N,X=X)
params <- c("beta")
model_string <- textConnection(
"model{
# Likelihood
for(i in 1:10){
Y[i] ~ dbinom(p[i],N[i])
logit(p[i]) <- beta[1] + beta[2]*X[i]
}

# Priors
beta[1] ~ dnorm(0,0.01)
beta[2] ~ dnorm(0,0.01)
}")
model <- jags.model(model_string,data = data, n.chains=3,quiet=TRUE)
update(model, 10000, progress.bar="none")
samples1 <- coda.samples(model, variable.names=params, thin=5, n.iter=20000)
summary(samples1)
plot(samples1)

```


